name: Pikafish

on:
  push:
    branches:
      - jieqi

jobs:
  Pikafish-Android:
    name: Android-${{ matrix.arch }}
    runs-on: ubuntu-latest
    env:
      ARCH: ${{ matrix.arch }}
      COMPCXX: aarch64-linux-android29-clang++
      COMP: ndk
      EXE: pikafish-${{ matrix.arch }}
      LDFLAGS: "-static -Wno-unused-command-line-argument"
    strategy:
      matrix:
        arch: ["armv8"]
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install qemu-user

      - name: Install NDK
        run: |
          NDKV="27.2.12479018"
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=$ANDROID_ROOT/sdk
          SDKMANAGER=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager
          echo "y" | $SDKMANAGER "ndk;$NDKV"
          ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/$NDKV
          ANDROID_NDK_BIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "ANDROID_NDK_BIN=$ANDROID_NDK_BIN" >> $GITHUB_ENV

      - name: Compile ${{ matrix.arch }} build
        run: |
          export PATH=${{ env.ANDROID_NDK_BIN }}:$PATH
          make -j profile-build EXE=$EXE WINE_PATH=$EMU
          make strip EXE=$EXE
          cp $EXE ../

      # Artifacts automatically get zipped.
      # To avoid double-zipping, we use the unzipped directory
      - uses: actions/upload-artifact@v4
        with:	
          name: Pikafish-Android-${{ matrix.arch }}
          path: |
            ${{ env.EXE }}
            AUTHORS
            CONTRIBUTING.md
            Copying.txt
            README.md
            Top CPU Contributors.txt