name: Pikafish

on:
  push:
    branches:
      - jieqi_old

jobs:	
  windows:	
    strategy:	
      matrix:	
        arch: ["-bmi2", "-modern"]	
    runs-on: windows-latest

    steps:	
      - uses: actions/checkout@v3	

      - name: make	
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64${{ matrix.arch }} EXE=pikafish${{ matrix.arch }}.exe && strip pikafish${{ matrix.arch }}.exe	

      - name: copy binary to folder
        run: mkdir windows && cp src/pikafish*.exe windows

      - uses: actions/upload-artifact@v3	
        with:	
          name: pikafish
          path: |
            windows/pikafish*
            AUTHORS
            Copying.txt
            NNUE-License.txt
            README.md
            Top CPU Contributors.txt

  linux:
    strategy:	
      matrix:	
        arch: ["-bmi2", "-modern"]	
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: make	
        run: cd src && make clean && make -j build COMP=gcc ARCH=x86-64${{ matrix.arch }} EXE=pikafish${{ matrix.arch }} && strip pikafish${{ matrix.arch }}

      - name: copy binary to folder
        run: mkdir linux && cp src/pikafish* linux

      - uses: actions/upload-artifact@v3	
        with:	
          name: pikafish	
          path: |
            linux/pikafish*
            AUTHORS
            Copying.txt
            NNUE-License.txt
            README.md
            Top CPU Contributors.txt